
  {
    "error_code": 0,
    "msg":"查询成功",
    "data": {
      "uid": "1",
      "userName": "杨婷",
      "account":"账号",
      "headPic": "http://tva1.sinaimg.cn/crop.0.0.996.996.180/7725b907jw8f58qgyio04j20ro0ro41d.jpg",
      "level": 2 ,
      "department": "知识信息管理部",
      "sex":"男",
      "post":"职务",
      "position":"职位",
      "title":"职称",
      "organizationLocation":"组织位置",
      "entryTime":"2015-06-01",
      "workPlace":"工作地点",
      "officeLocation":"办公位置",
      "mobilePhone":"手机",
      "telephone":"电话",
      "landLine":"座机",
      "fax":"传真",
      "mailbox":"邮箱",
      "projectExperience":"项目经验",
      "qualification":" 资格证书",
      "winningRecord":"获奖记录",
      "hobby":"爱好专长",
      "goldCount": 100,
      "collectionCount":10,
      "circleCount":10,
      "collectionAbleClick":true,
      "dynamicCount":2000,
      "dynamicAbleClick":true
    }
  }